analyzer:
  errors:
    avoid_dynamic_calls: ignore
    cascade_invocations: ignore
    inference_failure_on_function_invocation: ignore
    library_private_types_in_public_api: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
    unnecessary_cast: ignore
    unnecessary_to_list_in_spreads: ignore
    avoid_positional_boolean_parameters: ignore
    unrelated_type_equality_checks: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
    use_build_context_synchronously: ignore
    avoid_slow_async_io: ignore
    unnecessary_await_in_return: ignore
    no_default_cases: ignore
    avoid_redundant_argument_values: ignore
    unawaited_futures: ignore
    only_throw_errors: ignore
    parameter_assignments: ignore
    inference_failure_on_instance_creation: ignore
    deprecated_member_use: ignore
    inference_failure_on_untyped_parameter: ignore
    omit_local_variable_types: ignore
    avoid_print: ignore
    prefer_final_locals: ignore
    use_late_for_private_fields_and_variables: ignore
    unused_element: ignore
    inference_failure_on_function_return_type: ignore
    depend_on_referenced_packages: ignore
    prefer_single_quotes: ignore
    unused_local_variable: ignore
    noop_primitive_operations: ignore
    non_constant_identifier_names: ignore
    constant_identifier_names: ignore
    unnecessary_parenthesis: ignore
    unnecessary_const: ignore
    unused_field: ignore
    avoid_unused_constructor_parameters: ignore
    flutter_style_todos: ignore
    use_colored_box: ignore
    unnecessary_lambdas: ignore
    avoid_escaping_inner_quotes: ignore
    unnecessary_string_escapes: ignore
    use_key_in_widget_constructors: ignore
    library_prefixes: ignore

include: package:very_good_analysis/analysis_options.6.0.0.yaml
