name: jsps_depo
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.3.0
  connectivity_plus: ^6.0.3
  coordinate_converter: ^1.1.1
  firebase_app_check: ^0.3.0+5
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_storage: ^12.2.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_pdfview: ^1.3.2
  geolocator: ^12.0.0
  get: ^4.6.6
  google_generative_ai: ^0.4.0
  google_sign_in: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  translator_plus: ^1.0.1
  url_launcher: ^6.2.6
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ayyildiz.png
    - assets/terms.json
  fonts:
    - family: JspsDepom
      fonts:
        - asset: assets/fonts/JspsDepom.ttf
