// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJXQlnB9K8voBn8ZMumNTattrhiK0X6Pg',
    appId: '1:989021201314:android:4c564b3c321fb76c4d08fb',
    messagingSenderId: '989021201314',
    projectId: 'jspsdepo-9d5ea',
    storageBucket: 'jspsdepo-9d5ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAezMdHoWcttEIbLM6W8HtqAlcyV9CS1jc',
    appId: '1:989021201314:ios:3bf5b243894777ae4d08fb',
    messagingSenderId: '989021201314',
    projectId: 'jspsdepo-9d5ea',
    storageBucket: 'jspsdepo-9d5ea.appspot.com',
    androidClientId: '989021201314-56qbl6mquuevnud40e8ni4ffrgd9kuli.apps.googleusercontent.com',
    iosClientId: '989021201314-bnprpsrdjddl3pnjrk0jlv6j2203sv4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.jspsDepo',
  );

}